/**
 * @fileoverview gRPC-Web generated client stub for pathologyrpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.0
// source: pathology.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var base_pb = require('./base_pb.js')
const proto = {};
proto.pathologyrpc = require('./pathology_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pathologyrpc.HelloClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pathologyrpc.HelloPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.HelloRequest,
 *   !proto.pathologyrpc.HelloResponse>}
 */
const methodDescriptor_Hello_SayHello = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Hello/SayHello',
  grpc.web.MethodType.UNARY,
  base_pb.HelloRequest,
  base_pb.HelloResponse,
  /**
   * @param {!proto.pathologyrpc.HelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  base_pb.HelloResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.HelloResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.HelloResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.HelloClient.prototype.sayHello =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Hello/SayHello',
      request,
      metadata || {},
      methodDescriptor_Hello_SayHello,
      callback);
};


/**
 * @param {!proto.pathologyrpc.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.HelloResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.HelloPromiseClient.prototype.sayHello =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Hello/SayHello',
      request,
      metadata || {},
      methodDescriptor_Hello_SayHello);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pathologyrpc.CoreClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pathologyrpc.CorePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.StartRequest,
 *   !proto.pathologyrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_Start = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/Start',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.StartRequest,
  proto.pathologyrpc.CoreInfoResponse,
  /**
   * @param {!proto.pathologyrpc.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.start =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/Start',
      request,
      metadata || {},
      methodDescriptor_Core_Start,
      callback);
};


/**
 * @param {!proto.pathologyrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.start =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/Start',
      request,
      metadata || {},
      methodDescriptor_Core_Start);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.Empty,
 *   !proto.pathologyrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_CoreInfoListener = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/CoreInfoListener',
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.pathologyrpc.CoreInfoResponse,
  /**
   * @param {!proto.pathologyrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.CoreInfoResponse>}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.coreInfoListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pathologyrpc.Core/CoreInfoListener',
      request,
      metadata || {},
      methodDescriptor_Core_CoreInfoListener);
};


/**
 * @param {!proto.pathologyrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.CoreInfoResponse>}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CorePromiseClient.prototype.coreInfoListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pathologyrpc.Core/CoreInfoListener',
      request,
      metadata || {},
      methodDescriptor_Core_CoreInfoListener);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.Empty,
 *   !proto.pathologyrpc.OutboundGroupList>}
 */
const methodDescriptor_Core_OutboundsInfo = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/OutboundsInfo',
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.pathologyrpc.OutboundGroupList,
  /**
   * @param {!proto.pathologyrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.OutboundGroupList.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.outboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pathologyrpc.Core/OutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_OutboundsInfo);
};


/**
 * @param {!proto.pathologyrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CorePromiseClient.prototype.outboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pathologyrpc.Core/OutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_OutboundsInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.Empty,
 *   !proto.pathologyrpc.OutboundGroupList>}
 */
const methodDescriptor_Core_MainOutboundsInfo = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/MainOutboundsInfo',
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.pathologyrpc.OutboundGroupList,
  /**
   * @param {!proto.pathologyrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.OutboundGroupList.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.mainOutboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pathologyrpc.Core/MainOutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_MainOutboundsInfo);
};


/**
 * @param {!proto.pathologyrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CorePromiseClient.prototype.mainOutboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pathologyrpc.Core/MainOutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_MainOutboundsInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.Empty,
 *   !proto.pathologyrpc.SystemInfo>}
 */
const methodDescriptor_Core_GetSystemInfo = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/GetSystemInfo',
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.pathologyrpc.SystemInfo,
  /**
   * @param {!proto.pathologyrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.SystemInfo.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.SystemInfo>}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.getSystemInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pathologyrpc.Core/GetSystemInfo',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemInfo);
};


/**
 * @param {!proto.pathologyrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.SystemInfo>}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CorePromiseClient.prototype.getSystemInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pathologyrpc.Core/GetSystemInfo',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.SetupRequest,
 *   !proto.pathologyrpc.Response>}
 */
const methodDescriptor_Core_Setup = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/Setup',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.SetupRequest,
  proto.pathologyrpc.Response,
  /**
   * @param {!proto.pathologyrpc.SetupRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.Response.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.SetupRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.setup =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/Setup',
      request,
      metadata || {},
      methodDescriptor_Core_Setup,
      callback);
};


/**
 * @param {!proto.pathologyrpc.SetupRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.Response>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.setup =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/Setup',
      request,
      metadata || {},
      methodDescriptor_Core_Setup);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.ParseRequest,
 *   !proto.pathologyrpc.ParseResponse>}
 */
const methodDescriptor_Core_Parse = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/Parse',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.ParseRequest,
  proto.pathologyrpc.ParseResponse,
  /**
   * @param {!proto.pathologyrpc.ParseRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.ParseResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.ParseRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.ParseResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.ParseResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.parse =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/Parse',
      request,
      metadata || {},
      methodDescriptor_Core_Parse,
      callback);
};


/**
 * @param {!proto.pathologyrpc.ParseRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.ParseResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.parse =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/Parse',
      request,
      metadata || {},
      methodDescriptor_Core_Parse);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.ChangeClientSettingsRequest,
 *   !proto.pathologyrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_ChangeClientSettings = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/ChangeClientSettings',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.ChangeClientSettingsRequest,
  proto.pathologyrpc.CoreInfoResponse,
  /**
   * @param {!proto.pathologyrpc.ChangeClientSettingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.ChangeClientSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.changePathologySettings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/ChangeClientSettings',
      request,
      metadata || {},
      methodDescriptor_Core_ChangeClientSettings,
      callback);
};


/**
 * @param {!proto.pathologyrpc.ChangeClientSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.changePathologySettings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/ChangeClientSettings',
      request,
      metadata || {},
      methodDescriptor_Core_ChangeClientSettings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.StartRequest,
 *   !proto.pathologyrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_StartService = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/StartService',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.StartRequest,
  proto.pathologyrpc.CoreInfoResponse,
  /**
   * @param {!proto.pathologyrpc.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.startService =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/StartService',
      request,
      metadata || {},
      methodDescriptor_Core_StartService,
      callback);
};


/**
 * @param {!proto.pathologyrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.startService =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/StartService',
      request,
      metadata || {},
      methodDescriptor_Core_StartService);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.Empty,
 *   !proto.pathologyrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_Stop = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/Stop',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.pathologyrpc.CoreInfoResponse,
  /**
   * @param {!proto.pathologyrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.stop =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/Stop',
      request,
      metadata || {},
      methodDescriptor_Core_Stop,
      callback);
};


/**
 * @param {!proto.pathologyrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.stop =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/Stop',
      request,
      metadata || {},
      methodDescriptor_Core_Stop);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.StartRequest,
 *   !proto.pathologyrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_Restart = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/Restart',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.StartRequest,
  proto.pathologyrpc.CoreInfoResponse,
  /**
   * @param {!proto.pathologyrpc.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.restart =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/Restart',
      request,
      metadata || {},
      methodDescriptor_Core_Restart,
      callback);
};


/**
 * @param {!proto.pathologyrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.restart =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/Restart',
      request,
      metadata || {},
      methodDescriptor_Core_Restart);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.SelectOutboundRequest,
 *   !proto.pathologyrpc.Response>}
 */
const methodDescriptor_Core_SelectOutbound = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/SelectOutbound',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.SelectOutboundRequest,
  proto.pathologyrpc.Response,
  /**
   * @param {!proto.pathologyrpc.SelectOutboundRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.Response.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.SelectOutboundRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.selectOutbound =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/SelectOutbound',
      request,
      metadata || {},
      methodDescriptor_Core_SelectOutbound,
      callback);
};


/**
 * @param {!proto.pathologyrpc.SelectOutboundRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.Response>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.selectOutbound =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/SelectOutbound',
      request,
      metadata || {},
      methodDescriptor_Core_SelectOutbound);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.UrlTestRequest,
 *   !proto.pathologyrpc.Response>}
 */
const methodDescriptor_Core_UrlTest = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/UrlTest',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.UrlTestRequest,
  proto.pathologyrpc.Response,
  /**
   * @param {!proto.pathologyrpc.UrlTestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.Response.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.UrlTestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.urlTest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/UrlTest',
      request,
      metadata || {},
      methodDescriptor_Core_UrlTest,
      callback);
};


/**
 * @param {!proto.pathologyrpc.UrlTestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.Response>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.urlTest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/UrlTest',
      request,
      metadata || {},
      methodDescriptor_Core_UrlTest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.GenerateWarpConfigRequest,
 *   !proto.pathologyrpc.WarpGenerationResponse>}
 */
const methodDescriptor_Core_GenerateWarpConfig = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/GenerateWarpConfig',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.GenerateWarpConfigRequest,
  proto.pathologyrpc.WarpGenerationResponse,
  /**
   * @param {!proto.pathologyrpc.GenerateWarpConfigRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.WarpGenerationResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.GenerateWarpConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.WarpGenerationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.WarpGenerationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.generateWarpConfig =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/GenerateWarpConfig',
      request,
      metadata || {},
      methodDescriptor_Core_GenerateWarpConfig,
      callback);
};


/**
 * @param {!proto.pathologyrpc.GenerateWarpConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.WarpGenerationResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.generateWarpConfig =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/GenerateWarpConfig',
      request,
      metadata || {},
      methodDescriptor_Core_GenerateWarpConfig);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.Empty,
 *   !proto.pathologyrpc.SystemProxyStatus>}
 */
const methodDescriptor_Core_GetSystemProxyStatus = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/GetSystemProxyStatus',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.pathologyrpc.SystemProxyStatus,
  /**
   * @param {!proto.pathologyrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.SystemProxyStatus.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.SystemProxyStatus)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.SystemProxyStatus>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.getSystemProxyStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/GetSystemProxyStatus',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemProxyStatus,
      callback);
};


/**
 * @param {!proto.pathologyrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.SystemProxyStatus>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.getSystemProxyStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/GetSystemProxyStatus',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemProxyStatus);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.SetSystemProxyEnabledRequest,
 *   !proto.pathologyrpc.Response>}
 */
const methodDescriptor_Core_SetSystemProxyEnabled = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/SetSystemProxyEnabled',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.SetSystemProxyEnabledRequest,
  proto.pathologyrpc.Response,
  /**
   * @param {!proto.pathologyrpc.SetSystemProxyEnabledRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.Response.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.SetSystemProxyEnabledRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.setSystemProxyEnabled =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.Core/SetSystemProxyEnabled',
      request,
      metadata || {},
      methodDescriptor_Core_SetSystemProxyEnabled,
      callback);
};


/**
 * @param {!proto.pathologyrpc.SetSystemProxyEnabledRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.Response>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.CorePromiseClient.prototype.setSystemProxyEnabled =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.Core/SetSystemProxyEnabled',
      request,
      metadata || {},
      methodDescriptor_Core_SetSystemProxyEnabled);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.Empty,
 *   !proto.pathologyrpc.LogMessage>}
 */
const methodDescriptor_Core_LogListener = new grpc.web.MethodDescriptor(
  '/pathologyrpc.Core/LogListener',
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.pathologyrpc.LogMessage,
  /**
   * @param {!proto.pathologyrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.LogMessage.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.LogMessage>}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CoreClient.prototype.logListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pathologyrpc.Core/LogListener',
      request,
      metadata || {},
      methodDescriptor_Core_LogListener);
};


/**
 * @param {!proto.pathologyrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.LogMessage>}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.CorePromiseClient.prototype.logListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pathologyrpc.Core/LogListener',
      request,
      metadata || {},
      methodDescriptor_Core_LogListener);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pathologyrpc.TunnelServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pathologyrpc.TunnelServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.TunnelStartRequest,
 *   !proto.pathologyrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Start = new grpc.web.MethodDescriptor(
  '/pathologyrpc.TunnelService/Start',
  grpc.web.MethodType.UNARY,
  proto.pathologyrpc.TunnelStartRequest,
  proto.pathologyrpc.TunnelResponse,
  /**
   * @param {!proto.pathologyrpc.TunnelStartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.TunnelResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.TunnelStartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.TunnelServiceClient.prototype.start =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.TunnelService/Start',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Start,
      callback);
};


/**
 * @param {!proto.pathologyrpc.TunnelStartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.TunnelServicePromiseClient.prototype.start =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.TunnelService/Start',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Start);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.Empty,
 *   !proto.pathologyrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Stop = new grpc.web.MethodDescriptor(
  '/pathologyrpc.TunnelService/Stop',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.pathologyrpc.TunnelResponse,
  /**
   * @param {!proto.pathologyrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.TunnelResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.TunnelServiceClient.prototype.stop =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.TunnelService/Stop',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Stop,
      callback);
};


/**
 * @param {!proto.pathologyrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.TunnelServicePromiseClient.prototype.stop =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.TunnelService/Stop',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Stop);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.Empty,
 *   !proto.pathologyrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Status = new grpc.web.MethodDescriptor(
  '/pathologyrpc.TunnelService/Status',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.pathologyrpc.TunnelResponse,
  /**
   * @param {!proto.pathologyrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.TunnelResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.TunnelServiceClient.prototype.status =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.TunnelService/Status',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Status,
      callback);
};


/**
 * @param {!proto.pathologyrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.TunnelServicePromiseClient.prototype.status =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.TunnelService/Status',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Status);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pathologyrpc.Empty,
 *   !proto.pathologyrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Exit = new grpc.web.MethodDescriptor(
  '/pathologyrpc.TunnelService/Exit',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.pathologyrpc.TunnelResponse,
  /**
   * @param {!proto.pathologyrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pathologyrpc.TunnelResponse.deserializeBinary
);


/**
 * @param {!proto.pathologyrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pathologyrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pathologyrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pathologyrpc.TunnelServiceClient.prototype.exit =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pathologyrpc.TunnelService/Exit',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Exit,
      callback);
};


/**
 * @param {!proto.pathologyrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pathologyrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.pathologyrpc.TunnelServicePromiseClient.prototype.exit =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pathologyrpc.TunnelService/Exit',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Exit);
};


module.exports = proto.pathologyrpc;

