package masque

// MasqueDocumentedEnvVars is the canonical registry of MASQUE/HIDDIFY_MASQUE knobs read in
// production Go (non-test). Keep sorted; extend when adding os.Getenv for a new knob.
// Hygiene gate: TestMasqueDocumentedEnvVarsExist (H-S22).
var MasqueDocumentedEnvVars = []string{
	"HIDDIFY_MASQUE_CONNECT_IP_DEBUG",
	"HIDDIFY_MASQUE_DATAGRAM_CEILING_MAX",
	"HIDDIFY_MASQUE_TCP_HTTP3_LEGACY_DATAGRAMS",
	"MASQUE_CONNECT_IP_BOOTSTRAP_REQUIRE_PREFIX",
	"MASQUE_CONNECT_IP_OBS",
	"MASQUE_CONNECT_IP_SKIP_BOOTSTRAP_CAPSULES",
	"MASQUE_CONNECT_IP_TCP_NETSTACK_PREFIX_WAIT_SEC",
	"MASQUE_CONNECT_STREAM_DIAL_BACKOFF_MS",
	"MASQUE_CONNECT_STREAM_DIAL_MAX_ATTEMPTS",
	"MASQUE_H2_BIDI_BOOTSTRAP_UPLOAD_BYTES",
	"MASQUE_H2_BIDI_DOWNLOAD_DRAIN",
	"MASQUE_H2_BIDI_UPLOAD_WAKE",
	"MASQUE_H2_CONNECT_STREAM_NEW_TRANSPORT_PER_DIAL",
	"MASQUE_H2_CONNECT_UDP_ASYMMETRIC_DUPLEX",
	"MASQUE_H2_CONNECT_UDP_UPLOAD_STREAMS",
	"MASQUE_H2_CONNECT_UPLOAD_BULK_FLUSH",
	"MASQUE_H2_CONNECT_UPLOAD_CHUNK",
	"MASQUE_H2_DOWNLOAD_EAGER_WINDOW",
	"MASQUE_H3_BIDI_BOOTSTRAP_UPLOAD_BYTES",
	"MASQUE_H3_BIDI_DOWNLOAD_DRAIN",
	"MASQUE_H3_BIDI_DOWNLOAD_WAKE",
	"MASQUE_H3_BIDI_UPLOAD_WAKE",
	"MASQUE_QUIC_DOWNLOAD_EAGER_WINDOW",
	"MASQUE_QUIC_HANDSHAKE_IDLE_MS",
	"MASQUE_QUIC_KEEPALIVE_MS",
	"MASQUE_QUIC_PACKET_CONN_POLICY",
	"MASQUE_QUIC_WAKE_SEND_ON_RECEIVE_READ",
	"MASQUE_RELAY_LOG_HIJACK",
	"MASQUE_TRACE_TCP",
}
